### ISSUE TITLE
Disqus

### ISSUE THREAD

**Issue by jigs1212** [biomadeira/sustain#4]
What are the steps to set disqus. i mean what all variables i need to set
Thanks.

**Comment by jigs1212** [comment]
Thanks it is solved :+1:

**Comment by RobertMyles** [comment]
Hi @jigs1212 

Could you tell me please how you managed to integrate Disqus with the sustain theme? I'm having a bit of trouble doing it. I've entered my shortname in the `disqus.html` file. I see that there are two other places I should probably edit:
```{}
var disqus_identifier = '{{ page.url}}';
var disqus_url = '{{ site.url }}{{ page.url }}';
```
but I'm not too sure what needs to go in these parts. Any ideas?

**Comment by RobertMyles** [comment]
Don't worry, figured it out, thanks!
